# joint_ids_map: [0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11,
#   17, 24, 18, 25, 19, 26, 20, 27, 21, 28]

# <<------------- Joint ------------->> 
# Joint_index: 0, name: left_hip_pitch_joint
# Joint_index: 1, name: left_hip_roll_joint
# Joint_index: 2, name: left_hip_yaw_joint
# Joint_index: 3, name: left_knee_joint
# Joint_index: 4, name: left_ankle_pitch_joint
# Joint_index: 5, name: left_ankle_roll_joint
# Joint_index: 6, name: right_hip_pitch_joint
# Joint_index: 7, name: right_hip_roll_joint
# Joint_index: 8, name: right_hip_yaw_joint
# Joint_index: 9, name: right_knee_joint
# Joint_index: 10, name: right_ankle_pitch_joint
# Joint_index: 11, name: right_ankle_roll_joint
# Joint_index: 12, name: waist_yaw_joint
# Joint_index: 13, name: waist_roll_joint
# Joint_index: 14, name: waist_pitch_joint
# Joint_index: 15, name: left_shoulder_pitch_joint
# Joint_index: 16, name: left_shoulder_roll_joint
# Joint_index: 17, name: left_shoulder_yaw_joint
# Joint_index: 18, name: left_elbow_joint
# Joint_index: 19, name: left_wrist_roll_joint
# Joint_index: 20, name: left_wrist_pitch_joint
# Joint_index: 21, name: left_wrist_yaw_joint
# Joint_index: 22, name: right_shoulder_pitch_joint
# Joint_index: 23, name: right_shoulder_roll_joint
# Joint_index: 24, name: right_shoulder_yaw_joint
# Joint_index: 25, name: right_elbow_joint
# Joint_index: 26, name: right_wrist_roll_joint
# Joint_index: 27, name: right_wrist_pitch_joint
# Joint_index: 28, name: right_wrist_yaw_joint


# joint_ids_map: [0, 6, 12,
#                 1, 7, 13,
#                 2, 8, 14,
#                 3, 9    , 15, 22,
#                 4, 10   , 16, 23,
#                 5, 11   , 17, 24,
#                           18, 25,
#                           19, 26,
#                           20, 27,
#                           21, 28]
# step_dt: 0.02
# # stiffness: [200.0, 200.0, 200.0,
# #             150.0, 150.0, 200.0,
# #             150.0, 150.0, 200.0,
# #             200.0, 200.0       , 100.0, 100.0,
# #               20.0,  20.0       , 100.0, 100.0,
# #               20.0,  20.0       ,  50.0,  50.0,
# #                                   50.0,  50.0,
# #                                   40.0,  40.0,
# #                                   40.0,  40.0,
# #                                   40.0,  40.0]
# stiffness: [200.0, 150.0, 150.0, 200.0, 20.0, 20.0,
#             200.0, 150.0, 150.0, 200.0, 20.0, 20.0, 
#             200.0, 200.0, 200.0,
#             100.0, 100.0, 50.0, 50.0, 40.0, 40.0, 40.0,
#             100.0, 100.0, 50.0, 50.0, 40.0, 40.0, 40.0]

# damping: [5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
#           5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
#           5.0, 5.0, 5.0,
#           2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
#           2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,]

# default_joint_pos: [-0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
#                     -0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
#                     0.0, 0.0, 0.0,
#                     0.35, 0.18, 0.87, 0.0, 0.0, 0.0, 0.0,
#                     0.35, 0.18, 0.87, 0.0, 0.0, 0.0, 0.0]

# joint_ids_map: [0, 6, 12,
#                     1, 7, 13,
#                     2, 8, 14,
#                     3, 9    , 15, 22,
#                     4, 10   , 16, 23,
#                     5, 11   , 17, 24,
#                               18, 25,
#                               19, 26,
#                               20, 27,
#                               21, 28]
joint_ids_map: [0, 1, 2, 3, 4, 5, 
                6, 7, 8, 9, 10, 11,
                12, 13, 14, 
                15, 16, 17, 18, 19, 20, 21, 
                22, 23, 24, 25, 26, 27, 28]
step_dt: 0.02
stiffness: [200.0, 200.0, 200.0,
            150.0, 150.0, 200.0,
            150.0, 150.0, 200.0,
            200.0, 200.0       , 100.0, 100.0,
              20.0,  20.0       , 100.0, 100.0,
              20.0,  20.0       ,  50.0,  50.0,
                                  50.0,  50.0,
                                  40.0,  40.0,
                                  40.0,  40.0,
                                  40.0,  40.0]
damping: [5.0, 5.0, 5.0,
        5.0, 5.0, 5.0,
        5.0, 5.0, 5.0,
        5.0, 5.0     , 2.0, 2.0,
        2.0, 2.0     , 2.0, 2.0,
        2.0, 2.0     , 2.0, 2.0,
                        2.0, 2.0,
                        2.0, 2.0,
                        2.0, 2.0,
                        2.0, 2.0]
# stiffness: [200.0, 150.0, 150.0, 200.0, 20.0, 20.0,
#             200.0, 150.0, 150.0, 200.0, 20.0, 20.0, 
#             200.0, 200.0, 200.0,
#             100.0, 100.0, 50.0, 50.0, 40.0, 40.0, 40.0,
#             100.0, 100.0, 50.0, 50.0, 40.0, 40.0, 40.0]

# damping: [5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
#           5.0, 5.0, 5.0, 5.0, 2.0, 2.0,
#           5.0, 5.0, 5.0,
#           2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
#           2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,]

# default_joint_pos: [-0.20, -0.20,  0.0,
#                      0.00,  0.00,  0.0,
#                      0.00,  0.00,  0.0,
#                      0.42,  0.42      , 0.35,  0.35,
#                     -0.23, -0.23      , 0.18, -0.18,
#                      0.00,  0.00      , 0.00,  0.00,
#                                       0.87,  0.87,
#                                       0.00,  0.00,
#                                       0.00,  0.00,
#                                       0.00,  0.00]
default_joint_pos: [-0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
                    -0.2, 0.0, 0.0, 0.42, -0.23, 0.0,
                    0.0, 0.0, 0.0,
                    0.35, 0.18, 0.87, 0.0, 0.0, 0.0, 0.0,
                    0.35, 0.18, 0.87, 0.0, 0.0, 0.0, 0.0]

commands:
  base_velocity:
    ranges:
      lin_vel_x: [-0.5, 1.0]
      lin_vel_y: [-0.3, 0.3]
      ang_vel_z: [-0.2, 0.2]
      heading: null
actions:
  JointPositionAction:
    clip: null
    joint_names: [.*]
    # scale: [0.25, 0.25,                   0.25,
    #         0.25, 0.25,                   0.25,
    #         0.25, 0.25,                   0.25,
    #         0.25, 0.25      , 0.25, 0.25,
    #         0.25, 0.25      , 0.25, 0.25,
    #         0.25, 0.25      , 0.25, 0.25,
    #                           0.25, 0.25,
    #                           0.25, 0.25,
    #                           0.25, 0.25,
    #                           0.25, 0.25]
    scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    joint_ids: [0, 6, 12,
                1, 7, 13,
                2, 8, 14,
                3, 9    , 15, 22,
                4, 10   , 16, 23,
                5, 11   , 17, 24,
                          18, 25,
                          19, 26,
                          20, 27,
                          21, 28]

observations:
  obs:
    use_gym_history: true
    base_ang_vel:
      params: {}
      clip: null
      scale: [1.0, 1.0, 1.0]
      history_length: 10
    projected_gravity:
      params: {}
      clip: null
      scale: [1.0, 1.0, 1.0]
      history_length: 10
    velocity_commands:
    # keyboard_velocity_commands:
      params: {command_name: base_velocity}
      clip: null
      scale: [1.0, 1.0, 1.0]
      history_length: 10
    joint_pos_rel:
      params: {}
      clip: null
      scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
        1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      history_length: 10
    joint_vel_rel:
      params: {}
      clip: null
      scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
        1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      history_length: 10
    last_action:
      params: {}
      clip: null
      scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
        1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      history_length: 10

